### ISSUE TITLE
Navbar css, utf-8 kódolás minden fájlban.

### ISSUE THREAD

**Issue by viatour** [viatour/hamzse#8]
Szar a mozzilla, ezért kell az utf-8as kódolás minden html fájlba. Valamint célszerű lenne egységesen tárolni a navbar css fájlát. Így ha éppen kéne változtatni rajta valamit, akkor elég lenne csak ott átírni.

**Comment by hamzse** [comment]
https://pcforum.hu/hirek/19007/elkepeszto-mennyisegu-penzt-keresett-a-firefox-szal-a-mozilla

**Comment by viatour** [comment]
A navbar css fájl megvan külön.

**Comment by viatour** [comment]
Megoldva
